apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: roommate-frontend-hpa
    namespace: roommate
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: roommate-frontend
    minReplicas: 1
    maxReplicas: 3
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 70
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: 80
    behavior:
        scaleUp:
            stabilizationWindowSeconds: 60
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 60
        scaleDown:
            stabilizationWindowSeconds: 300
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: roommate-backend-hpa
    namespace: roommate
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: roommate-backend
    minReplicas: 1
    maxReplicas: 4
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 70
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: 80
    behavior:
        scaleUp:
            stabilizationWindowSeconds: 60
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 60
        scaleDown:
            stabilizationWindowSeconds: 300
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 60
