apiVersion: v1
kind: ConfigMap
metadata:
    name: mongo-init
    namespace: roommate
data:
    init-mongo.js: |
        db = db.getSiblingDB('Roommate');
        db.createUser({
          user: 'admin-user',
          pwd: 'AdminPassword',
          roles: [
            { role: 'readWrite', db: 'Roommate' }
          ]
        });

        db.createUser({
          user: "user",
          pwd: "SecretPassword",
          roles: [
            {
              role: "readWrite",
              db: "Roommate"
            }
          ]
        });

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mongo-config
    namespace: roommate
data:
    mongod.conf: |
        storage:
          dbPath: /data/db
        net:
          bindIp: 0.0.0.0
          port: 27017
        security:
          authorization: enabled
