apiVersion: v1
kind: Namespace
metadata:
    name: roommate
    labels:
        name: roommate
        environment: production

---
apiVersion: v1
kind: ResourceQuota
metadata:
    name: roommate-quota
    namespace: roommate
spec:
    hard:
        requests.cpu: "2"
        requests.memory: 2Gi
        limits.cpu: "4"
        limits.memory: 4Gi
        pods: "10"
