apiVersion: v1
kind: Secret
metadata:
    name: mongo-secrets
    namespace: roommate
type: Opaque
data:
    MONGO_INITDB_ROOT_USERNAME: YWRtaW4tdXNlcg==
    MONGO_INITDB_ROOT_PASSWORD: QWRtaW5QYXNzd29yZA==
    MONGO_INITDB_DATABASE: Um9vbW1hdGU=
    MONGO_USER: dXNlcg==
    MONGO_PASSWORD: U2VjcmV0UGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: roommate
type: Opaque
stringData:
    DATABASE_URI: "mongodb://user:SecretPassword@mongo-0.mongo-headless.roommate.svc.cluster.local:27017/Roommate?retryWrites=true&w=majority"
    ACCESS_TOKEN_SECRET: "542b2fd4b17be8c5667d1458be67345f5fceb70cc95257fc8db4278892dc66b2606608bbfd6f321a9bc2628077eb2ec63192cf2752cf90dcd056b7b845f58181"
    REFRESH_TOKEN_SECRET: "eb0b9f9527e6c726a14565622e5141962ad10d27800183b165d96e800a3e1cd67cc7381bf1686c0f4e3cd363ad67995cd3fb7fc2b69e670b5e7afdb2e10b4b9d"

---
apiVersion: v1
kind: Secret
metadata:
    name: frontend-secrets
    namespace: roommate
type: Opaque
stringData:
    API_BASE_URL: "http://roommate.local/api"
